// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://firfwpammvhmgfyjzeii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcmZ3cGFtbXZobWdmeWp6ZWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTMwMDksImV4cCI6MjA2MjY4OTAwOX0.m963Ugnh9o6dNHG07WYumW69-Ye63xo8j_vTyhRc3Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);